openapi: 3.0.0
info:
  title: LaraLite API
  version: 1.0.0
servers:
  - url: http://localhost:2000
paths:
  /index.php/v1/curso:
    post:
      tags:
        - cursos
      summary: registrar curso
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nombre: Introducción a la Programación
                ponentes: Juan Pérez
                descripcion: >-
                  Este curso proporciona una introducción básica a los conceptos
                  fundamentales de la programación.
                fechaInicio: '2025-02-01'
                fechaFin: '2025-02-28'
                capacidad: 50
                certificado: Constancia
                estado: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - cursos
      summary: actualizar curso
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 3
                nombre: Introducción a la Programación
                ponentes: Jorge
                descripcion: >-
                  Este curso proporciona una introducción básica a los conceptos
                  fundamentales de la programación.
                fechaInicio: '2025-02-01'
                fechaFin: '2025-02-28'
                capacidad: 50
                certificado: Constancia
                estado: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - cursos
      summary: listar curso
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /index.php/v1/curso/eliminar:
    post:
      tags:
        - cursos
      summary: eliminar curso
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}